### ISSUE TITLE
It can't get BeiDou solution result by rtkconv and rtkpost which can get by rtknav.

### ISSUE THREAD

**Issue by Deginch** [tomojitakasu/RTKLIB#172]
There is no BeiDou result when I use rtkconv and rtkpost, which I can get it by rtknav with same settings.

**Comment by divid54** [comment]
I think you can comment this line "if (m==3&&rtk->opt.bdsmodear==0) continue;" in function "ddmat" in rtkpos.c and rebuild the app. If it not works, check the BeiDou time in eph.toe.

**Comment by dsgida** [comment]
I am using NV08C-CSM latest hardware version 5 which has 2 optional firmwares, GPS + GLONASS & GPS + BEIDOU
I am using GPS+BEIDOU firmware. The problem is that when I choose GPS,BEIDOU & SBAS from RTKNAVI options,only GPS satellites are chosen & seen. Beidou satellites are not seen & taken into account for the solution. SBAS sattelites are also not seen( only letter "G"is seen in the RTKNAVI window) . There is not such problem with GLONASS sattelites. Can anyone provide solution to this problem ? When I use Hemisphere A100 smart antenna (which is a GPS+SBAS receiver ) , both GPS & SBAS sattelites are seen ( letter "GS" is seen in the RTKNAVI window). I am using RTKLIB 2.4.2 patch 11 software version.

With regards,
Dhirendra singh,
INDIA.
