### ISSUE TITLE
STRSVR commands at startup

### ISSUE THREAD

**Issue by PellePettersson** [tomojitakasu/RTKLIB#213]
I can not find the right commands at startup from STRSVR for this:
Turn off NMEA child messages
Turn on RXM-RAWX
Turn on RXM-SFRBX
I am having an Ublox neo M8T
I can manage to do this with u-center but want to do it at power on.
!UBX CFG-MSG 2 21 0 0 0 1 0 0 (RXM-RAWX on USB-port,  Is that so?)
!UBX CFG-MSG 2 19 0 0 0 1 0 0 (RXM-SFRBX on USB-port,  Is that so?)
But how to turn off NMEA ?

**Comment by tomojitakasu** [comment]
(1) I recommend to use UBX-CFG-CFG by u-center to save the options to flash after setting the output messages by UBX-CFG-MSG.
(2) On Windows 10 (or 8/8.1), you may have trouble that UBX-CFG-MSG cannot disable NMEA in case that u-blox is recognized as a device "u-blox GNSS Location Sensor". To solve the problem, you have to replace the "u-blox GNSS Location Sensor" driver by the Windows standard USB serial device's one.

**Comment by PellePettersson** [comment]
Thanks tomojitakasu!
One dumb question...Can I send RTCM3 direct from GPS receiver and sending it from a base to a rover with RTKNAVI, without using STRSVR in the base?

**Comment by astrodanco** [comment]
Yes, if you have a receiver that outputs RTCM3. Just about any survey grade receiver can output RTCM3.

**Comment by DavidKelleySCSC** [comment]
[And neo M8T is not survey grade, so no.]  But in both cases (inexpensive vs costly) be sure to shut down message traffic in an orderly way when the device is turned off.  RTKLIB has a command sequence to do this for you. you can copy and paste from the u-center tools to use it.   Otherwise any GNSS may be sending more than you intended. I have been called on many times by 'pros' to look at "intermittently working" data streams where the root cause is sending unwanted NMEA content along with the RTCM3 content.  Best practice: set it up each and every time you power on.  Use the monitor ability in RTKLIB to confirm the stream is what you want and **only** what you want.

**Comment by PellePettersson** [comment]
OK!
Then I do not need to read raw data and convert it to RTCM3 with STRSVR before I send it to Rover. 
I can directly send RTCM3 to rover then.
OR, is it possibly to ONLY read RTCM3 from GPS Receiver and pass it thru STRSVR?
Then I can turn off RXM-RAWX and RXM-SFRBX, or?
If sending RTCM3 from receiver, which one to use?
F5-05 RTCM3.1 1005
F5-4D RTCM3.1 1077
F5-57 RTCM3.1 1087
Is there any disadvantages with this? (Instead of using RXM-RAWX and RXM-SFRBX)
Will RTK Kinematic have the same accuracy?

**Comment by DavidKelleySCSC** [comment]
I think you misunderstood (more likely I am being unclear).    If your GNSS is a uBlox (6 or 8) then
> I do not need to read raw data and convert it to RTCM3 with STRSVR before I send it to Rover.
> I can directly send RTCM3 to rover then.

Is **not** correct. as it does **not** output anything but the uBlox **RAW** format.  You **must** translate. There are a number of tools that can translate from that format to various RTCM3 messages, and you will need to do this.  STRSVR is of course your best choice to do so.  
Phrases like "_F5-57 RTCM3.1 1087_" do not seem to make sense to me (I see it on another blob post), but you seem to want to use the MSM message 1087 etc. (which is fine and RTKLIB supports).  All you need to do for STRSVR is tell it the messages you want ("1004(1).. or "1087(1)...") and ensure it gets the raw data it needs (i.,e have the uBlox send it out in that format).  

>Instead of using RXM-RAWX and RXM-SFRBX)  .. Will RTK Kinematic have the same accuracy?

A good but complex question.  Probably.  As far as I am aware the STRSVR translation does not compromise the data in any way. MSM messages are better then older 1004 only messages, as you get the direct Doppler data.  But you are proposing to use an L1 only device as your base station so your operational baselines need to be under 10k or so.  Buy a good antenna.  If you are ONLY going to send to one device, you might stay in the native uBlox format. But is you want to share (i.e. a caster or multiple end users, use the industry standard formats - that what we created it for).

**Comment by tomojitakasu** [comment]
Direct output of RTCM 3 MSM (MT1077, MT1087 and MT1127) and MT1005 is only supported by u-blox M8P (M8P-0 or M8P-2). It is unavailable by other M8 or older modules.

https://www.u-blox.com/en/product/neo-m8p

At this moment (ES2), M8P does not support Galileo/QZSS, RTCM ephemeris messages and 10 Hz. So I still recommend M8T (F/W 3.01 is needed for Galileo and 10 Hz) with UBX-RXM-RAWX/SFRBX.

**Comment by DavidKelleySCSC** [comment]
tomojitakasu is correct and I was wrong and am out of date (guess we need to buy another round of chips here).   Thus there is no convert process step (once the device is setup), only a send process.

**Comment by PellePettersson** [comment]
I think I will stop messing around, I will configure ublox M8T (as I have already) to send UBX-RXM-RAWX/SFRBX. and reading that with STRSVR (Win10) and transfer it wireless to my 3 Rovers.
Could you please suggest a suitable HW and SW-solution to do that work. (Caster?)

I have 3 Rovers (Tractors) that need Base-data and will be around 2-3000m from Base. (I am a Poor Farmer :-) with a big interest of this) 
So far, I am at this point in my project testing a solution where I have the following setup:
Base with M8T sending UBX-RXM-RAWX/SFRBX at 115200 bps to a laptop with STRSVR. Sending ublox over TCP (No RTCM#3 translation) 
Rover with an other M8T sending UBX-RXM-RAWX/SFRBX at 115200bps.
I will get FLOAT in RTKNAVI but never FIX.
I'm in an open area. When standing at one point I will get FLOAT within 10-15 cm (NOT FIX). However when I start moving It starts to jump 10-15m in all directions and FLOAT disappear.
How to solve this? 
Setup in Rover: 
Setting1: Kinematic, L1+L2, Elev mask 15, GPS GLO SBAS
Setting2: Cont.
Positions: Lat63.xxxxxx, Lon21.xxxxxxx,H10.0 (Northen Europe)

**Comment by CGEOS** [comment]
The problem is not RTK-LIB and parameters etc, ... but the ublox ! ublox is promoting and selling chips that have no the required quality for performing RTK properly. There have been many trials and attempts but this is the reality. It took years in development for getting RTK fix for many companies and to make it reliable. Ublox is very much attracting on pricing (and promises) but the reality is different. You can keep going on your project but by using i.e. the K500 board from ComNav Technology ... If you are interested, I can help and support you. Joël

**Comment by tomojitakasu** [comment]
Dear PellePettersson,
Try the following settings.
Elevation mask: 20 - 30
Navigation System: GAL ON, SBAS OFF 
Integer Ambiguity Res: Fix and Hold, OFF, ON

Dear CGEOS,
I have different opinion from yours. I have tested many receivers with RTKLIB including Trimble, NovAtel, Javad, Hemisphere, u-blox and NVS, Unfortunately no experience of ComNav.
For low-cost L1 RTK performance, refer:
http://gpspp.sakura.ne.jp/paper2005/isgps2008_paper_ttaka.pdf
Note that it was written 8-years ago. The situation has been changed.

**Comment by DavidKelleySCSC** [comment]
To PellePettersson; your setup can feed the three rovers with RTKLIB and a TCP connection alone.  You do not need a caster (much as that hurts me to say ;) because you only have one stream.  You can use one if you want (go look at our firm's free one at use-snip.com) but you do not need one.   On the whole, and baring ant blocked sky issues you should be able to get such a distance fixing well into >90% of the time.

I think I also disagree with CGEOS painting such a bleak picture.  In gross terms, uBlox tracking is ~5x more crude than survey grade, but we are speaking of several mm here.  And they continue to get better.  And yes I still prefer to use a high grade L1/L2 board when conditions allow.  For what it is worth, I have been building automotive RTK for nearly 30 years now (came from military GPS), and 6 years ago I started to use RTKLIB in my own work.  And I have watched many L1 vs L1/L2 battles over these years.  Even 6 years ago, the results we saw with ublox+RTKLIB and only a few additional tricks added to it were much better than the paper tomojitakasu cites.  [Regrettably those tricks are the topics of various patents]  _All in all_ I happens to think uBlox and RTKLIB together are great tools to bring RTK out for the mass market.  It has moved the price point of a short baseline reference station to under 1k, and that us really something.  Just what a "Poor Farmer" needs.  My 2 cents.

**Comment by coandrei** [comment]
No intention to offend anybody. 
ComNav K500, K508 OEM board and their related accessories have entered the end of life (EOL) phase
http://www.comnavtech.com/news-detail.asp?id=81&bigclassid=140&sw=1280&sh=800
