### ISSUE TITLE
Trimble asti Rover and 

### ISSUE THREAD

**Issue by juffe84** [tomojitakasu/RTKLIB#341]
I have rover Trimble R10 with Trimble Access operating system. I'm trying to get a make base station with ublox neo m8t and strsvr. I have Snip program as a caster. when i connect to the caster by trimble, everything works fine but trimble says that correction age is "?" Trimble says that solution is "Autono", but data is coming from Caster. When I connect to commercial base station, age is 1sec and solution is RTK. What kind of messages do i need to get right solution? Maybe specific ublox startup commands or specific rtcm message needed?

**Comment by astrodanco** [comment]
Are you converting the UBLOX raw to RTCM3? RTCM3 is what the Trimble receiver is going to need to see. What sort of antenna is the UBLOX using and does ACCESS have a profile for it so that you can get the correct phase center offset?

**Comment by DavidKelleySCSC** [comment]
> I'm trying to get a make base station base station with ublox neo m8t and strsvr. I have SNIP program as a caster.
It is not 100% clear to me if "but data is coming from Caster" refers to SNIP, but if it does, just right click on the stream in question and select "Show Message Types" and tell us what you see.    If you are getting RTCM3 you will see messages like 1004,  1012, etc.  If you are getting raw uBlox you will see long binary messages starting with "RXM" in it.   Trimble accepts RTCM 2.x, 3.x, and CMR but not raw uBlox.
If you are not getting RTCM3 message to the SNIP Caster (presumable from STRSVR), be sure you are telling to convert to RTCM3 and giving it a set of requested message such as "1004(1)"

**Comment by juffe84** [comment]
Strsvr is convert ublox to rtcm3. SNIP receive 1004, 1005, 1006, 1008, 1012, 1033 with 25 satellite. I have tallysman antennia with ublox. Trimble Access receive data, cos bits counter moving Access and SNIP.  In Access i have profile RTK rtcm3.  (Tomorrow I can send pictures of my settings) 

"What sort of antenna is the UBLOX using and does Access have a profile for it so that you can get the correct phase center offset?" 

Where I can set phase center profile?

**Comment by DavidKelleySCSC** [comment]
That all sounds correct to me, and more or less matches the advice at [here](https://www.use-snip.com/kb/knowledge-base/using-strsvr-from-rtklib-with-snip/) and the only thing that occurs to me that the data the Trimble R10 is getting not well-formed or perhaps complete messages.  Please try the above to confirm that you have valid messages being sent. If you can see messages, confirm your 1005/1006 message is giving a reasonable position with the RTCM [message decoder](https://www.use-snip.com/kb/knowledge-base/using-the-rtcm3-decoder-dialog/) dialog.  If you still have issues please send an email to support@use-snip.com  And then you can adjust for the Tallysman antenna model for last little bit.

**Comment by juffe84** [comment]
![image 1](https://user-images.githubusercontent.com/32144019/30682019-b208dd98-9eb0-11e7-8176-4e305e43956c.png)
![image](https://user-images.githubusercontent.com/32144019/30682020-b2099b98-9eb0-11e7-91ec-7928c3d83930.png)
![image 2](https://user-images.githubusercontent.com/32144019/30682021-b20b4d4e-9eb0-11e7-8bd7-a274f1ba3fe4.png)

**Comment by juffe84** [comment]
STR;juha;;RAW;Unknown;;;SNIP;;;;0;0;sNTRIP;None;N;N;0; 
Im streaming my data to rtk2go.com:2101 if you want check if my stream is valid

**Comment by DavidKelleySCSC** [comment]
juffe84:  
I am reading the stream off the RTK2go site now, and just displaying what I see with SNIP's built in tools.  A couple of things come up.  First, understand **that in RTK double difference modes, what the Base Station says is the word of God**.  If its reported position is offset from 'truth' (often by a meter or so due to different datum issues), the Rover just aligns to that and take the resulting error residuals out in trade.  

But here, see image below, you have enter very crude values that are in fact way off.  This alone will prevent getting a fix, and may wholesale data rejection.   Such crude values belong only in the Caster table, where they are simply used as a guide to help others find the right base station [for SNIP, it will sent that up that string for you]. There are a number of support article on the use-snip.com/kb support site, but this is an RTKLIB forum so it seems improper to promote our commercial products here.   

Please look at the below screen shots. One of the models of SNIP provides a very nice "tool tip" to see details about the Base Station.  Those nice round LLH values look very suspect.
![juhabasestationttooltips](https://user-images.githubusercontent.com/5143060/30709114-f05c449a-9eb5-11e7-831e-df367955b821.png)

That was the first clue to me.  Then I used SNIPs simple least squares navigation filter (which by the way was modeled after the one in RTKLIB) to show me what your data resolved to and plotted that as well.  As the below shows, your real location is far different from your reported ECEF in the message stream, **it is in error by ~30km**.  
![juhabasestationscreenshot](https://user-images.githubusercontent.com/5143060/30709184-3bcbf024-9eb6-11e7-9b24-56fcce0a1379.png)

So what you need to do is set the uBlox ECEF value to be more like the ECEF values resulting from 63.07038985 / 21.6587809 / 50  At least until you can make a 4+ hour run and get more precise values to use.  [Read up on OPUS and then find what the local equal to it would be]

One other odd think strikes me, and this is not to be critical but...  Are you using a fairly good Trimble R10 L1/L2 device as you Rover device while using a uBlox L1 only device as your Base?  Seems a bit backwards, at least in terms of cost.  I have no idea how the Trimble will react with no L2 data, but will try to do that test here once I come back from travel to a convention next week. If your R10 is set up only for L1, then you can skip this remark, as the raw tracking ability of the uBlox is remarkably good.

**Comment by DavidKelleySCSC** [comment]
juffe84:
Please post an update for the group (and close this is you feel it is working).  When I last looked at your "juha" data stream on the RTK2go.com site you had corrected the EFEC data and it all seemed to be working to me.  But the stream disappeared soon thereafter.  Are you getting good fixed ratios now?   

[And on another matter, using L1 only corrections sourced from a uBlox on a higher end L1/L2 rover unit and with RTKLIB/RTKNAVI seemed to work fine when I tried it this morning, but of course it converges at L1 only speeds]

**Comment by juffe84** [comment]
OK. I test next week.

30.9.2017 10.51 ip. "DC Kelley" <notifications@github.com> kirjoitti:
