### ISSUE TITLE
Problems in reading rinex 3.xx with 0.000 entities

### ISSUE THREAD

**Issue by holmnikolaj** [tomojitakasu/RTKLIB#352]
In the rinex obs reader the fixed priority of channel results in unused data if different satellites uses different channels.

Attached is an example where some gps satellites uses C2W L2W S2W and D2W and some uses C2X L2X S2X and D2X. The satellites that uses the X channels are all disregarded on L2 due to priority of channels. 

[B102609dot17o.txt](https://github.com/tomojitakasu/RTKLIB/files/1457215/B102609dot17o.txt)

Would a fix that checks if values are 0.000 and chooses the other channel if available solve the issue without causing troubles further on in the processing?

**Comment by tomojitakasu** [comment]
RTKLIB does not support mixture of different codes in a frequency for processing. It is because receivers have some bias (DCB) between different codes, that makes offset in DD measurements. So you can use only one code per a frequency.
To change the default priority of these codes to read RINEX, use Options - Misc - RINEX opt (Rover or Base) for RTKNAVI or misc-rnxopt1 or rnxopt2 for RNX2RTKP. The details of the RINEX options, refer the header comments of function readrnxt() in RTKLIB/src/rinex.c.

**Comment by holmnikolaj** [comment]
Does that apply even if some GPS satellite always uses C2W L2W S2W and D2W and some other satellites always uses C2X L2X S2X and D2X? 
I ask because when the same log is converted to rinex 2.11 instead of 3.02 the different codes are "merged" into C2, P2, L2 and S2 using the non-zero entities for all satellites, and so mixing what is seperated as "x" and "w" codes in rinex 3.02.

Attached the same log as 2.11 to show the point:
[B102609dot17o.txt](https://github.com/tomojitakasu/RTKLIB/files/1457754/B102609dot17o.txt)

**Comment by tomojitakasu** [comment]
Yes.
RINEX 2.11 cannot distinguish L2P(Y) and L2C (or L1P(Y) and L1C/A) for carrier-phase. So RTKLIB merges input L2P(Y) and L2C to L2 in RINEX 2.11. That means RINEX 2.11 cannot be properly processed with both of L2P(Y) and L2C. RINEX 2.11 should not be used for mixture data of L2P(Y) and L2C.
