### ISSUE TITLE
Remove binaries from the source tree

### ISSUE THREAD

**Issue by nunojpg** [tomojitakasu/RTKLIB#49]
Please consider moving Binaries out from the source tree (at /bin) to the GitHub Releases feature.

Having binaries at the source tree is highly disruptive since a "git clone" size will increase significantly at each release.

**Comment by nunojpg** [comment]
Current git repository is 173MB large. It is really a problem in some situations. Removing all the large binaries history will require a repository rewrite, which is also a problem. I believe it is better to do it sooner than later, since the problem needs to be eventually addressed. I so recall this issue so you can carefully consider it for the next release as you said. Thanks!

**Comment by firegurafiku** [comment]
I second that issue.
Also, please consider switching to a build system which supports out-of-source builds. I'd suggest CMake for being cross-platform and already adopted by many FOSS projects. I can tackle this task if you don't mind.

**Comment by tomojitakasu** [comment]
The contents of RTKLIB/bin have been moved to RTKLIB_bin/bin. The history of RTKLIB/bin in old repositories are also deleted.

**Comment by tomojitakasu** [comment]
No plan to use CMAKE, which does not support GUI AP projects.

**Comment by firegurafiku** [comment]
@tomojitakasu 

If you mean that CMake isn't able to build C++ Builder's projects linking to VCL, I cannot name you a piece of free software which is. VCL and C++ Builder are separate vendor lock-in problem.

**Comment by tomojitakasu** [comment]
Sorry. I don't understand what you want to say.
CMAKE supports the C++ builder project?

**Comment by firegurafiku** [comment]
AFAIK, CMake cannot build C++ Builder project, and nothing besides C++ Builder can.
I just said that using proprietary compiler, IDE and visual component library in open source development is a problem per se. And they're not only proprietary, one can buy an airplane for their license price. Maybe it's worth considering switching to another window toolkit, which is free and cross-platform?

**Comment by tomojitakasu** [comment]
OK. I understand.
When I started the RTKLIB project abut 10 years ago, I selected the C++ builder for RTKLIB GUI APs by two reasons.

(1) Borland released a free-version of full-set C++ builder. MS VS did not support GUI APs at that moment.
(2) I had had several projects using C++ builder. The IDE and toolkit (VCL) are powerful and easier to use compared to others.

Anyway, time goes by. Borland has gone. Embbacadero sells C++ builder with expensive price tags.

I agree your opinion, that an open-source project should not depend on proprietary products. However, please understand that a lot of efforts are needed to change the platform. Some RTKLIB users requested me to change the toolkit to Qt. Qt seems better at this moment. But Qt is also a proprietary product. I'm not sure the future.

It is hard to change the toolkit by myself just because of my time constraint. JensReimann started the project to port RTKLIB APs on Qt. (Thanks Jens.) It may be an alternative solution.

https://github.com/JensReimann/rtklib-qt

Thanks for your frank suggestion for RTKLIB.

**Comment by firegurafiku** [comment]
Thank you for detailed answer, and for pointing me to `rtklib-qt`!

Yes, I understand that the project is quite old, and it's hard to redesing lots of screen forms (I've counted more than fifty DFM files in the repo), so I really don't want you to see me somewhat pushy.

> But Qt is also a proprietary product.

It's already not. Qt is being LGPL dual-licensed for years, there is no option to close the source once opened even if they decide to focus development only on the proprietary version.

**Comment by tomojitakasu** [comment]
I understand the current situation.
But in my understandings, it does not mean the future version Qt is ensured to be LGPL.

**Comment by nunojpg** [comment]
Just my two cents.

At this time I believe the best option for a rtklib GUI would be a HTML5 implementation (with Angular or so) like so many applications are doing now (For example Linux Cockpit), with the corresponding  web services in C++.

In any case the only opinion that really matters is of the one that takes the step forward to implement it, and at this time, I'm not in that position.

(and I'm now closing this issue since it has been taken care)

Thanks!
