### ISSUE TITLE
deq() is different from GLONASS ICD v5.1

### ISSUE THREAD

**Issue by achenjw** [tomojitakasu/RTKLIB#492]
xdot[5] in fuction deq() as as well as describled in the manual doc is a little different from it in GLONASS ICD 2008 v5.1.

**Comment by tomojitakasu** [comment]
The GLONASS ephemeris computation in RTKLIB is based on A.3.1.2 of the GLONASS ICD ed. 5.1 (2008). However, the ICD ed. 5.1 (2008) has multiple versions (!) and some version has well-known errata as follows. 

(1) The sign of the fourth term for dV_y/dt should be minus instead of plus.
(2) The first coefficient in the bracket of the second term for dV_z/dt should be 3 instead of 1.

http://gauss.gge.unb.ca/GLONASS.ICD.pdf
https://kb.unavco.org/kb/article/english-version-of-icd-glonass-version-5-1-727.html

In some version, the errata are already fixed as like follows. RTKLIB complies with the fixed version.

[ICD_GLONASS_5.1_eng_201402.pdf](https://github.com/tomojitakasu/RTKLIB/files/3657985/ICD_GLONASS_5.1_eng_201402.pdf)

**Comment by achenjw** [comment]
got it,thank you so much for the reply!
