### ISSUE TITLE
STRSVR: Method of spreading out data bursts for RF transmission

### ISSUE THREAD

**Issue by m-elias** [tomojitakasu/RTKLIB#619]
I'm using STRSRV with the convert option to control which RTCM3 msgs get sent and at what frequency over my RF RTK correction link. If I use the following:
1074(2),1084(2),1094(2),1124(2),1006(19),1008(20),1033(21)
I get a large burst every 2 seconds for the four main constellations. At a marginal distance from my base, I often observe that my rover receives the first msg (1074) but not the other three. Is there a method to spread out the msgs so that they still get sent every X seconds but are offset from each other? I have been thinking maybe a way to specify an offset, in my case, 0/0.5/1/1.5 second offsets for the four main msgs respectively.

**Comment by m-elias** [comment]
I have considered slowing down the serial baud into my transmitting base station radio, I will see how that works.

**Comment by DavidKelleySCSC** [comment]
Sorry this will not work as you expect, if the limit is in fact the RF data rate and not some serial or comm link buffer. The navigation filter in the the GNSS wants all the observational messages (in this case MSM MT10x4) at the same time (they are time stamped) in order to run.  This is a problem with LoRa as well.   You can disable MT1084 or MT1124 and see if that gives statistically better results, but you lose those constellations.  In the case of the legacy messages (MT1014/1012) the last message has a flag to indicate that all the observations have been sent, if that last message is not received, none of the data is never used.
