### ISSUE TITLE
What is Periodic Commands(STRSVR) in "str2str"?

### ISSUE THREAD

**Issue by zhangL2auto** [tomojitakasu/RTKLIB#635]
I have a problem, can someone help me! Thanks a lot!

I can use "periodic commands" in STRSVR and receive messages.
But I dont know, how to deal with this "periodic commands" in STR2STR?

Command in STRSVR
![1](https://user-images.githubusercontent.com/84847407/141728415-53ce23f1-0c56-4adc-b7c6-7990209dcaf2.jpg)
Command in STR2STR    the command is -c or others?
![2](https://user-images.githubusercontent.com/84847407/141728426-90ccea78-5303-4bcf-9ce8-6bd2a72d860c.jpg)

Thanks!

**Comment by zhangL2auto** [comment]
Can someone help me? What is the Command of STRSVR in STR2STR?

**Comment by zhangL2auto** [comment]
@tomojitakasu 
I am so sorry to bother you, but I tried many times, and it doesn't work!
Can you tell me how to use " "periodic commands" in STRSVR " in STR2STR?

**Comment by lukegluke** [comment]
@zhangL2auto, instead of trying calling something many times, it would be better to take a look on code. Everything is here.

Even in help comments it is mentioned that "-c" argument expects path to file. (_by the way you could also send commands to output streams_)
https://github.com/tomojitakasu/RTKLIB/blob/180043ee24b6d2b168f98b64be15f69d50046b1a/app/consapp/str2str/str2str.c#L97

Than if we follow this further in code:
https://github.com/tomojitakasu/RTKLIB/blob/180043ee24b6d2b168f98b64be15f69d50046b1a/app/consapp/str2str/str2str.c#L256

We will see that there commands of type 0 (commands on start), 1 (commands on stop) and 2 (periodic commands) are read from file:
https://github.com/tomojitakasu/RTKLIB/blob/180043ee24b6d2b168f98b64be15f69d50046b1a/app/consapp/str2str/str2str.c#L315-L318
https://github.com/tomojitakasu/RTKLIB/blob/180043ee24b6d2b168f98b64be15f69d50046b1a/app/consapp/str2str/str2str.c#L338-L340

Last step is to see how type of commands is set:
https://github.com/tomojitakasu/RTKLIB/blob/180043ee24b6d2b168f98b64be15f69d50046b1a/app/consapp/str2str/str2str.c#L182-L199

According to this blocks of commands must be divided by line with @ symbol.
So create a file:
```
<start command1>
<start command2>
@
<periodic command1> # <period>
<periodic command2> # <period>
@
<stop command1>
<stop command2>

```
and run str2str with argument "-c 'path to this file'"

**Comment by aniugeaniusao** [comment]
邮件已经收到，我会及时回复，谢谢！
