### ISSUE TITLE
Rinex 3.02 "swallows" dual-frequency data

### ISSUE THREAD

**Issue by renanista** [tomojitakasu/RTKLIB#664]
Hello,

I have a problem with Rinex 3.02 using a file containing dual-frequencies. 
I'm recording my data using a dual-frequency receiver and later transforming them using convbin. 
When I convert them to Rinex 2.11 the output file is created correctly containing data of both frequencies. However, when I use 
-v 3.02 I get an output file but without the data from the second frequency. 

For later processing I need to use Rinex 3.02 so I would really appreciate if anyone knew a solution to this problem. What causes this error?

Best Regards,
Renan

**Comment by Waley04** [comment]
Hi Renan,

I want to reproduce the issue. I, therefore, wonder if you could provide a sample file you were trying to convert. 

Regards,

Waley.

**Comment by renanista** [comment]
Hey,

thank you for your help! 
I'll provide you a zip with the raw data. 
[rawdata.zip](https://github.com/tomojitakasu/RTKLIB/files/8941671/rawdata.zip)

First we used the .sh function to call convbin. It's basically: 
`convbin -od -os -oi -ot -ol -f 2 -v ver 3.02 -r ubx "$FILE"`
![ubx2rinexsh](https://user-images.githubusercontent.com/69856948/174629083-e79f2efc-86ea-463a-a2f0-d2e7f9a62614.png)

This resulted in the file which had 3.02 in it's header but lost the second frequency for some reason. You can find it under broken302file.obs in the zip. 
![header302broken](https://user-images.githubusercontent.com/69856948/174629518-88f53cc6-59e6-45a1-81fb-eb996d127df5.png)



Then I tried converting the file using convbin directly. I used the command:
`convbin -od -os -oi -ot -f 2 -v vers3.02 filename.ubx`
Now we got a file which had two frequencies but the header was 0.00 (I guess that's because it's still Rinex 2.11, it's called versionunknown.obs in the zip )
![wrongversion](https://user-images.githubusercontent.com/69856948/174629311-11012c8a-d548-4434-9e86-164a8b3e15fb.png)

Finally it worked fine using RTKConv GUI. We used the parameters in the picture and got the desired results 
![rtkconv2](https://user-images.githubusercontent.com/69856948/174628104-fb5af720-235e-4933-b81c-7948d6e3c8b0.PNG)


(rtkconv302_correct.obs in the zip)
![302_correct](https://user-images.githubusercontent.com/69856948/174630340-a33807f5-b585-41cb-b827-a482b5eaf6e6.png)

However, the question remains how we can call these parameters using convbin. It might be some error with -v
We wasn't sure whether it is -v vers 3.02, -v vers3.02 or -v vers302?

**Comment by Waley04** [comment]
Hi,

Many thanks for the sample data and details.

I tried to repeat the experiment by running the file using my customized script written in python.  

I managed the convert the *.ubx file to rinex 3.02 and 3.04. For simplicity, I renamed the *.ubx file to solo1556.ubx. Please, find attached the sample results. 

![ubx_rnx](https://user-images.githubusercontent.com/101952777/175780239-da59bcc3-d823-4906-a003-6293c7c1e9ca.PNG)

+++++ Sample Results =====
===> rinex_3.04
[rinex_3.04.zip](https://github.com/tomojitakasu/RTKLIB/files/8985062/rinex_3.04.zip)

To generate the rinex_3.02, I used a similar command to yours. Your command has an error : 

[ convbin -od -os -oi -ot -f 2 -v vers 3.02 filename.ubx ]

In this command,  you repeated the version (i.e, you passed both -v and ver). Since these are positional arguments, the software fails to recognize the second. This explains why the RINEX version decodes 0.00 in the output *.obs file. Revising this potion, I can generate the rinex 3.02 from your sample data. Please, refer to the attachment below:

===> rinex_3.02
[rinex_3.02.zip](https://github.com/tomojitakasu/RTKLIB/files/8985058/rinex_3.02.zip)

Hope this helps.

Regards,

Waley.

**Comment by renanista** [comment]
Hello,

Thank you very much!

So you used 
`convbin -od -os -oi -ot -f 2 -v 3.02 filename.ubx ]`

as a command?

Best regards,

**Comment by Waley04** [comment]
Hi,

Your command will work if you use any of the following:

1). convbin -od -os -oi -ot -f 2 -v 3.02 *.ubx   or
2). convbin -od -os -oi -ot -v 3.02 *.ubx
3). convbin  { and other parameters in addition to those specified in 1 and 2 above }

For ===> rinex_3.02, I used (convbin -od -os -oi -ot -v 3.02 *.ubx) and I used more parameters for the 3.04 (for demonstration purposes).

Thanks with regards.

**Comment by renanista** [comment]
Hello,

Finally I was able to create the right file. However, first using your command we had the same error. Finally we were able to fix this by forcing the terminal to run the convbin RTK-Lib Demo5 file. Before when we used convbin it reffered to an older version of RTKLib which has this "bug". 

Now we uninstalled the older RTKLib from the computer and it works fine.

Again thank you very much for your kind help :)

Best Regards,
Renan
