### ISSUE TITLE
Chi-Squared Solution Validation

### ISSUE THREAD

**Issue by franreal** [tomojitakasu/RTKLIB#98]
I've been taking more chi-square errors than expected, so I checked the error condition both in code and manual appendix E, founding what seems to be a discrepancy:

- In [manual_2.4.2](http://www.rtklib.com/prog/manual_2.4.2.pdf), page 160, E.6.33 divides the residuals by (m-n-1) for the test.

- In code, [src/pntpos.c](https://github.com/tomojitakasu/RTKLIB/blob/master/src/pntpos.c#L288-293), lines 288-293, the division is not -explicitly- performed.

In case this discrepancy is true, the validation test is tougher than needed.

**Comment by forrestv** [comment]
I believe that this is merely an error in the documentation. Looking at other descriptions of the chi-squared test, that division isn't present. Furthermore, there appears to be an off-by-one error in the documentation (not the code) for calculation of the degrees of freedom for the chi-squared distribution. Other descriptions specify it as `m-n`, but in the documentation it's `m-n-1`. It's `m-n-1` in the code because it's indexing a 0-based array (which matches the documentation, but shouldn't).

**Comment by Marszsu** [comment]
To be more precise, it is v*inv(Q)*v' has a chi-square distribution with degree of freedom m-n.  I believe the manual will be updated soon. Anyway everything in the code is almost correct. The v argument passed to function "valsol" is already weighted by its variances, but without considering the co-variances.  Does anyone has an investigation on the consequence of ignoring co-varainces? It will be nice to know.

**Comment by franreal** [comment]
I was secretly hoping it was a bug so I could have less chi-square errors... :)

Marszsu, I see your point in [src/pntpos.c](https://github.com/tomojitakasu/RTKLIB/blob/master/src/pntpos.c#L333-339), lines 333-339. Thank you and thank Forrest for your time and your answers.

About the co-variances investigation, I'm not an statistics expert and wouldn't know even how to start it. That could be a good topic for another issue, but I guess it's time to close this one.
